main:
  - identifier: nav.posts
    name: Posts
    pageRef: /posts
    weight: 20
    params:
      icon: posts
  - identifier: nav.projects
    name: Projects
    pageRef: /projects
    weight: 25
    params:
      icon: projects
  - identifier: nav.categories
    name: Categories
    pageRef: /categories
    weight: 30
    params:
      icon: categories
  - identifier: nav.tags
    name: Tags
    pageRef: /tags
    weight: 40
    params:
      icon: tags
  - identifier: nav.archives
    name: Archives
    pageRef: /archives
    weight: 50
    params:
      icon: archive

# footer menu
footer:
  - name: About
    pageRef: /about
    weight: 10
    params:
      icon: about
  - name: Contact
    url: https://google.com
    weight: 20
    params:
      icon: contact
  - name: RSS Feed
    url: /index.xml
    weight: 30
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/username
    weight: 10
    params:
      icon: github
  - name: Twitter
    url: https://twitter.com/username
    weight: 20
    params:
      icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/username
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:your.email@example.com
    weight: 40
    params:
      icon: email

